### ISSUE TITLE
Send Mail For Ansible Tower

### ISSUE THREAD

**Issue by aleyamayab** [infinitypp/ansible-mail-module-examples#1]
Hello, how would I like your help, I tell you that I am creating an email to send an attachment but it gives me an error:

my code:

- name: mail

  #Owner: IT Loyalty: Infrastructure Team | SRE Team
  #Last Update: March 2022
  #SRE Member Id: ayamaya

  hosts: 
   - tag_Name_ansibletower_lifemiles_loc

  serial: 0
  remote_user: lmadm

  vars: 
    report_file_name: /tmp/user/user_jira_test.csv

  tasks:

  - name: Send e-mail to a bunch of users, attaching files
    mail: 
      host: email-smtp.eu-west-1.amazonaws.com
      port: 25
      username: xxxxx
      password: xxxxx
      subject: Ansible-report-test
      body: Hello, this is an e-mail. I hope you like it ;-)
      from: nivel1soporte@domaind.com (Soporte Nivel 1)
      to:
      - alejandro bonilla <alejandro.bonilla@domaind.com>
      attach: /tmp/user/user_jira_test.csv
      headers:
      - Reply-To=alejandro.bonilla@domaind.com
      - X-Special="Something or other"
      charset: us-ascii
    delegate_to: localhost

![image](https://user-images.githubusercontent.com/100615826/184463545-2d9013b1-b200-4329-adbd-a9e1bd0e529a.png)

![image](https://user-images.githubusercontent.com/100615826/184463665-aa5e59d2-5040-46d9-91f6-0339688da968.png)

**Comment by soroushatarod** [comment]
not sure on this, but can you try getting the current directory outputed into a file?
